path: ../pre-data/data/v2i
train: train/images
val:   valid/images
test:  test/images

nc: 10
names:
  0: sau_duc_than      # Stem borer
  1: sau_cuon_la       # Leaf roller
  2: benh_dom_nau      # Brown spot
  3: benh_dao_on       # Blast
  4: benh_kho_van      # Sheath blight
  5: ran_xanh          # Green leafhopper
  6: bo_tri            # Thrips
  7: ran_nau           # Brown planthopper
  8: dom_la            # Leaf spot
  9: healthy           # Healthy leaf (hard negative)
